### ISSUE TITLE
swagger-ui中delete功能的测试不好用

### ISSUE THREAD

**Issue by zyyettie** [enilu/web-flash#1]
当前我们在Controller class中的定义是这样：
@RequestMapping(method = RequestMethod.DELETE)
public Object remove(Long id){
在swagger-ui中，测试该api时候，如果 我们在value中输入：
{id:1}
然后点击"Try it out"按钮。
这时候在Controller class中得到的id是null

**Comment by enilu** [comment]
https://github.com/enilu/web-flash/commit/0e9ff5f5cf676c53dd613ffec80d952a10abf830
