### ISSUE TITLE
JDK10+以上版本Maven编译会出错，需要手工指定lombok版本

### ISSUE THREAD

**Issue by CHN-STUDENT** [enilu/web-flash#18]
> 参考 https://blog.csdn.net/liubenlong007/article/details/86139598

我修改了 flash-core 模块 `pom.xml` 指定lombok版本1.18.4

```
<dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.4</version>
            <scope>compile</scope>
 </dependency>
```

做下记录，对可能会出现同样问题的人有所帮助，感谢！

**Comment by CHN-STUDENT** [comment]
@enilu 

另外我的navicat不支持建名字为`web-flash`的数据库，

我建为`webflash`的数据库，修改数据库配置文件后，程序帮我自动建表但**没有自动插入测试数据**

我手动插入数据MySQL给我`1366 - Incorrect string value: '\xE4\xB8\x80\xE8\x88\xAC...' for column 'content' at row 1` 错误。

![image](https://user-images.githubusercontent.com/21209416/62179857-86c8c080-b380-11e9-849c-c6d3258aa65d.png)

然后网上说此错误原因是数据库列编码设置问题？

![image](https://user-images.githubusercontent.com/21209416/62179892-a65fe900-b380-11e9-8095-28502f14c0be.png)

请帮助解决，谢谢您。

**Comment by enilu** [comment]
检查配置文件里数据库编码配置：
spring.datasource.url=jdbc:mysql://localhost:3306/webflash?useUnicode=true&characterEncoding=UTF8
spring.datasource.sql-script-encoding=utf-8

**Comment by CHN-STUDENT** [comment]
@enilu 我猜测可能是我windows系统mysql设置编码的原因
![image](https://user-images.githubusercontent.com/21209416/62193264-028b3300-b3aa-11e9-9265-e2b168172e14.png)
> 参考这篇文章修改：https://www.lovesofttech.com/database/mysql5.7ToUtf8mb4/
我最后修改了我mysql配置文件`my.ini`添加了以下的配置
```
[client]
default-character-set=utf8mb4

[mysqld]
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
init_connect='SET NAMES utf8mb4'
skip-character-set-client-handshake=false

[mysql]
default-character-set=utf8mb4
```

然后重启mysql服务器，删掉了原来所有表，系统重新帮我新建表并且再插入数据正常。
记录下给有同样情况的朋友们用。

![image](https://user-images.githubusercontent.com/21209416/62193511-79c0c700-b3aa-11e9-9340-f509d7ad7dcd.png)

**Comment by CHN-STUDENT** [comment]
此外在测试过程中，发现了可能会有以下的问题：

栏目管理添加应为栏目管理：
![image](https://user-images.githubusercontent.com/21209416/62195207-1173e480-b3ae-11e9-95c4-9ffa12dda86d.png)

CMS文章添加和编辑均有异常？
![image](https://user-images.githubusercontent.com/21209416/62195300-4aac5480-b3ae-11e9-8576-b9cdd5e1b586.png)
![image](https://user-images.githubusercontent.com/21209416/62195326-58fa7080-b3ae-11e9-88b0-5146e8115046.png)

联系管理就一个联系人？不知道是否需要增删改。

文件管理可能是查询和下载？

**Comment by enilu** [comment]
@CHN-STUDENT 错误原因不是有了么，检查下idChannel有没有传到后台，
联系人后台不做编辑，时候cms前端客户录入的，http://47.104.84.62:8080/mobile/#/contact
文件管理可以下载啊，查询暂时没空做，你有问题可以去qq群里问
