### ISSUE TITLE
前端项目npm run dev 后，浏览器控制台报错[Error] TypeError: Attempted to assign to readonly property. 

### ISSUE THREAD

**Issue by clouker** [enilu/web-flash#26]
[Error] TypeError: Attempted to assign to readonly property.
	(anonymous function) (app.js:114840)
	./node_modules/webpack-dev-server/client/clients/BaseClient.js (app.js:114856)
	__webpack_require__ (app.js:768)
	fn (app.js:131)
	(anonymous function) (app.js:114955)
	./node_modules/webpack-dev-server/client/clients/SockJSClient.js (app.js:115004)
	__webpack_require__ (app.js:768)
	fn (app.js:131)
	./node_modules/webpack-dev-server/client/socket.js (app.js:115387)
	__webpack_require__ (app.js:768)
	fn (app.js:131)
	(anonymous function) (app.js:115023)
	./node_modules/webpack-dev-server/client/index.js?http://localhost:9528 (app.js:115192)
	__webpack_require__ (app.js:768)
	fn (app.js:131)
	(anonymous function) (app.js:137143)
	__webpack_require__ (app.js:768)
	(anonymous function) (app.js:904)
	Global Code (app.js:905)

**Comment by aisidd** [comment]
我运行了没有问题， npm install多试几次，我用的node是12.14

**Comment by enilu** [comment]
此类问题就不要问了，自己看npm报错的时候给出的日志文件，根据相关日志进行排错，
