### ISSUE TITLE
前台编辑用户无修改密码功能。

### ISSUE THREAD

**Issue by CHN-STUDENT** [enilu/web-flash#28]
前台编辑用户无修改密码功能，后台接口却会修改？

![image](https://user-images.githubusercontent.com/21209416/65298801-673f5e80-db9f-11e9-8485-c64c7034b515.png)

![image](https://user-images.githubusercontent.com/21209416/65298758-4119be80-db9f-11e9-8345-ee43113018cd.png)

> https://github.com/enilu/web-flash/blob/master/flash-api/src/main/java/cn/enilu/flash/api/controller/system/UserController.java

**Comment by enilu** [comment]
前台编辑用户的时候不修改密码，后台也没有修改后台走下面逻辑没有修改密码：

`
 User oldUser = userService.get(user.getId());
 userService.update(UserFactory.updateUser(user,oldUser));
`
业务逻辑设计的不允许管理员修改密码，只允许用户自己登录自己账号在个人中心修改自己密码

**Comment by CHN-STUDENT** [comment]
@enilu 请问编辑管理员和编译用户是否走的是一个接口呢？

**Comment by enilu** [comment]
是同一个接口
