### ISSUE TITLE
定时任务模块cron在分钟级别会报时间表达式错误

### ISSUE THREAD

**Issue by sdksdk0** [enilu/web-flash#30]
定时任务表达式设置为0 0/2 * * * ?，会出现执行1次或者2次之后报时间表达式错误，然后就不再继续执行的问题。如果是小时级别的就不存在这个问题，可以正常执行。

![图片](https://user-images.githubusercontent.com/15673427/66981447-54f50980-f0e6-11e9-83e2-7e949b4ac948.png)

**Comment by enilu** [comment]
最新master分支已修复
