### ISSUE TITLE
菜单

### ISSUE THREAD

**Issue by 123114** [enilu/web-flash#31]
这个菜单没有多级目录呀，  前端是  vue-element-admin 的 ，后台是 guns  的？

**Comment by enilu** [comment]
是的，是的，是的

**Comment by XianYue-Tong** [comment]
@enilu 后面会考虑支持多级菜单吗？很多时候需要后台手动配置菜单目录，然后展示多层级菜单

**Comment by enilu** [comment]
系统支持根据权限显示菜单，你可以自己改造下支持多级菜单
