### ISSUE TITLE
如何修改某台默认上传文件大小以及传输header大小

### ISSUE THREAD

**Issue by CHN-STUDENT** [enilu/web-flash#32]
RT，文件只能上传10M之内的。
![image](https://user-images.githubusercontent.com/21209416/67375274-f4b60a00-f5b4-11e9-98d5-c8c6246e3c6e.png)
且文字过多会提示header过大
![image](https://user-images.githubusercontent.com/21209416/67375381-1e6f3100-f5b5-11e9-903f-57ccde996f3e.png)
没找到的这个配置文件

**Comment by enilu** [comment]
这问题自己百度下嘛
