### ISSUE TITLE
前端 ，界面中只要发生点击事件，element-ui不断报错

### ISSUE THREAD

**Issue by signorhua** [enilu/web-flash#37]
![image](https://user-images.githubusercontent.com/32768320/68835108-481e0280-06f2-11ea-924d-2705ec073b03.png)
![image](https://user-images.githubusercontent.com/32768320/68835131-51a76a80-06f2-11ea-9912-ceac4f5855c9.png)
##### 问题根源 <strong>el-dropdown嵌套导致</strong>
![image](https://user-images.githubusercontent.com/32768320/68835217-82879f80-06f2-11ea-91b1-1d62703a1adf.png)
##### 解决
![image](https://user-images.githubusercontent.com/32768320/68835382-df835580-06f2-11ea-915e-6ff27b797eb9.png)

**Comment by enilu** [comment]
@signorhua 赞一个， 提个PR噻
