### ISSUE TITLE
前端项目 --- store.getters 中缺少 permissions  解决自定义指令 v-permissions无效

### ISSUE THREAD

**Issue by signorhua** [enilu/web-flash#38]
补充代码
![image](https://user-images.githubusercontent.com/32768320/68852898-c6d76780-0713-11ea-8a1e-f61f34354878.png)
![image](https://user-images.githubusercontent.com/32768320/68853850-d8ba0a00-0715-11ea-8d39-4577aece787c.png)
![image](https://user-images.githubusercontent.com/32768320/68854710-9bef1280-0717-11ea-8b12-15327fcedeb9.png)

**Comment by enilu** [comment]
欢迎提PR
