### ISSUE TITLE
建表sql语句在哪？

### ISSUE THREAD

**Issue by InvisibleEmbrace** [enilu/web-flash#4]

**Comment by enilu** [comment]
系统启动自动创建表，初始化数据在flash-api/src/main/resources/import.sql

**Comment by localc** [comment]
数据库库名修改后是否不能创建表，单独的数据库web_flash,拥有增删改查和create,drop等权限，无自动创建表，将项目中三个建表语句添加create_by等通用4字段建表后，报web_flash.t_sys_dict doesn't exist
ERROR [SqlExceptionHelper]:142 Table 'web_flash.t_sys_dict' doesn't exist
