### ISSUE TITLE
按钮级别权限

### ISSUE THREAD

**Issue by guaisir** [enilu/web-flash#41]
控制按钮权限的显示隐藏权限不完善 不能隐藏权限按钮

**Comment by enilu** [comment]
请给出你问题的相关代码

**Comment by guaisir** [comment]
样例中各个页面中没有导入权限验证
`import permission from '@/directive/permission/index.js'`
所有新建角色用户后保存对应的按钮权限后也不会生效

**Comment by enilu** [comment]
参考user/index.vue中的用法
