### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by a878804506** [enilu/web-flash#50]
1、我看楼主项目里面自定义异常类型，遇到异常都会抛出ApplicationException类型的异常，但是出现这类异常后，并不会再t_sys_operation_log表中记录异常，这算是正常吗？
2、[文档](http://enilu.gitee.io/web-flash/feature/log.html#%E4%B8%9A%E5%8A%A1%E6%97%A5%E5%BF%97)此处有说明了异常处理类：GlobalExceptionHandler，但是我没在项目里找到？

**Comment by enilu** [comment]
t_sys_operation_log 表只记录管理员操作日志，不再记录异常日志，GlobalExceptionHandler 已经弃用。文档更新延后了，目前已经更新。
