### ISSUE TITLE
import的utils报错：Module is not installed

### ISSUE THREAD

**Issue by sunlechuan** [enilu/web-flash#6]
warning  in ./src/views/layout/components/Sidebar/Link.vue?vue&type=script&lang=js&

"export 'isExternal' was not found in '@/utils'

**Comment by wangh1998** [comment]
> warning in ./src/views/layout/components/Sidebar/Link.vue?vue&type=script&lang=js&
> 
> "export 'isExternal' was not found in '@/utils'
The same question.   How did you solve it?

**Comment by 23171580** [comment]
遇到同样的问题，@enilu vue项目运行需要特殊配置吗，还是需要特定版本npm包吗？
