### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by mayujin678** [enilu/web-flash#60]
![image](https://user-images.githubusercontent.com/24713069/83105218-dab14c80-a0ec-11ea-95c8-aa45ec998ae1.png)

**Comment by mayujin678** [comment]
Module parse failed: Unexpected character '#' (2:2)
You may need an appropriate loader to handle this file type.

**Comment by enilu** [comment]
警告信息而已，不用管；告警原因是它识别不了代码中的注释内容，如果看着碍眼，自行删除svgo.yml中的注释内容即可
