### ISSUE TITLE
前端启动的时候warning提示

### ISSUE THREAD

**Issue by aisidd** [enilu/web-flash#61]
WARNING  Compiled with 1 warnings                                                                                                                                      11:30:50 AM
 warning  in ./src/icons/svgo.yml

Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
> # replace default config
| # 基于svgo对svg文件进行压缩：https://panjiachen.github.io/vue-element-admin-site/zh/feature/script/svgo.html
| # multipass: true

 @ ./src sync ^\.\/.*$
 @ ./src/utils/route.js
 @ ./src/store/modules/menu.js
 @ ./src/store/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://10.219.40.21:9528/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

这里提示这个，但是目前不影响使用。。。百度没找到解决方案

**Comment by enilu** [comment]
参考 https://github.com/enilu/web-flash/issues/60

**Comment by DuanJiChao** [comment]
一样，删除注释，还是报错
