### ISSUE TITLE
修改表格数据bug

### ISSUE THREAD

**Issue by 1340007091** [enilu/web-flash#64]
可能是因为vue的数据绑定, 修改表格数据的时候, 如果修改了文本框的内容, 但是没有点击保存, 直接点击放弃或关掉dialog, 数据会回显到表格。
![image](https://user-images.githubusercontent.com/46468802/83958492-18f4fb80-a8a5-11ea-945b-73b311cd27c4.png)
![image](https://user-images.githubusercontent.com/46468802/83958501-3cb84180-a8a5-11ea-97b5-3afef1251fa3.png)
目前我的解决方案是用对象拷贝的方式
![image](https://user-images.githubusercontent.com/46468802/83958552-b7815c80-a8a5-11ea-8105-78d3735f15a1.png)

**Comment by enilu** [comment]
可以解决问题就行，我也不确定那种方案比较优雅，所以暂时没有解决

**Comment by enilu** [comment]
https://github.com/enilu/web-flash/commit/eef89b8cc8854c717a5ecf396ae13e43adf2e019#diff-ae3a16aae5f05a3176e75e01a041f193
