### ISSUE TITLE
shiro导致缓存注解失效

### ISSUE THREAD

**Issue by 1340007091** [enilu/web-flash#69]
在测试AccountController的info接口的时候，发现User user =  userService.get(idUser);每次都查询数据库,，不走缓存， 但是其它的service的缓存是正常走缓存的, 我尝试将缓存框架切换到redis发现userService的查询结果也没有成功存到redis，想起之前看到的一篇技术文章，说shiro的UserRealm依赖的service的事务注解会失效，所以猜想也是它导致缓存注解失效，我刚好记得解决方案是让UserRealm的service懒加载，即同时使用@Autowired +  @Lazy注解，问题成功解决。
![image](https://user-images.githubusercontent.com/46468802/86581588-e0833300-bfb2-11ea-9af1-d476b61f5e9a.png)

参考博客：https://blog.csdn.net/elonpage/article/details/78965176

**Comment by enilu** [comment]
你这个是老版本，新版本，我直接手动控制缓存了
https://github.com/enilu/web-flash/blob/master/flash-core/src/main/java/cn/enilu/flash/service/system/UserService.java

**Comment by 1340007091** [comment]
我用的是最新版本，AccountController里的info方法这里应该没有走手动控制的缓存。
![image](https://user-images.githubusercontent.com/46468802/87014073-2a138e00-c1fe-11ea-8391-a4ae607c264d.png)
