### ISSUE TITLE
代码生成插件无法生成代码

### ISSUE THREAD

**Issue by ShiBaoliang** [enilu/web-flash#70]
为避免无效问题和冗余问题，提问前请确认
1.你确定Google不能解决你的问题
  google搜索都是web-flash的在线介绍文档
2.你确定已有issue不能解决你的问题
  现有issue没有这个问题
3.你确定本项目readme和在线文档不能解决你的问题
  在线文档解释说让运行install打包，尝试没有效果
4.请按照如下格式提问问题

描述你遇到的问题
  按照文档说明步骤运行代码生成插件无法生成代码，测试用的是项目自带的Girl实体类
  PS：另外通过反编译发现代码生成插件的内部生成类的包路径是写死的，希望可以开放能够配置
  
![2](https://user-images.githubusercontent.com/20587932/86988476-e2274380-c1ca-11ea-9af7-1ac1a2a09b77.png)

如何重现问题
1.首先发现用IDEA插件商店安装的插件无法弹出web-flash mvc，故选用了项目中的插件jar包安装；
2.安装后install全工程成功；
3.选择Girl类，alt+Ins弹出web-flash mvc，默认点ok，代码无法生成；
![1](https://user-images.githubusercontent.com/20587932/86988494-ea7f7e80-c1ca-11ea-9d15-b27cb2855f62.png)

4.本人IDEA版本是2020.1.2，初步怀疑是不是版本问题？

期待修复的效果
1.代码生成插件能够正常生成代码
2.如果可以，不知道是否能够开源插件的代码，能够让大家一起学习，如果不便，不强求

如有必要，可以截图说明

版本说明
最新master分支

**Comment by enilu** [comment]
参考这个解决试试：http://bbs.enilu.cn/bbs/yvr/t/3ppacejvj4h3rpeaflkkuuhsuv

**Comment by enilu** [comment]
插件代码，我找找了，在旧电脑上

**Comment by enilu** [comment]
插件源代码：https://gitee.com/enilu/webflash-generator

**Comment by linkmancheng** [comment]
> 参考这个解决试试：http://bbs.enilu.cn/bbs/yvr/t/3ppacejvj4h3rpeaflkkuuhsuv

这链接访问不了了
