### ISSUE TITLE
菜单层级

### ISSUE THREAD

**Issue by KINGGUOKUN** [enilu/web-flash#74]
两个问题，请大神不吝赐教：
1、树状无线层级菜单支持；
2、顶级直接为页面导航菜单而不是目录；

这两种情况目前是不是都还不支持？谢谢啦~

**Comment by enilu** [comment]
不支持，短期内暂不考虑支持，欢迎提pr

**Comment by xiechengxii** [comment]
大神，请问一下，用户管理 角色管理的前端页面.vue文件在哪里呀，再views里面找了半天没找到
