### ISSUE TITLE
请问流程图编辑页面的前端代码在哪里

### ISSUE THREAD

**Issue by dannyxu2015** [enilu/web-flash#90]
例如这个资源在哪里？
```
flash-vue-admin/public/bpmnjs/index.js:var _activiti = _interopRequireDefault(require("../resources/properties-panel/provider/activiti"));
```
似乎找不到"../resources/properties-panel/provider/activiti" 这个资源

**Comment by enilu** [comment]
https://github.com/enilu/web-flash/blob/master/flash-vue-admin/public/bpmnjs/index.js

**Comment by burnszp** [comment]
你好，你的邮件我已经收到。
