### ISSUE TITLE
在 flash-vue-admin 中使用 npm install --registry=https://registry.npmmirror.com 时报错

### ISSUE THREAD

**Issue by ljguo1020** [enilu/web-flash#93]
在 flash-vue-admin 中使用 npm install --registry=https://registry.npmmirror.com 时报错，如下图
![Snipaste_2023-09-18_19-01-09](https://github.com/enilu/web-flash/assets/93716675/d7c7c7a7-6770-4409-a067-563ea8e5fd25)
请问应该如何解决，谢谢

**Comment by burnszp** [comment]
你好，你的邮件我已经收到。

**Comment by enilu** [comment]
你好，截图中错误信息已经支出，node-gyp工具需要依赖python，请按照提示进行安装
